"""
Mock STT provider for offline unit and integration testing without downloading model weights.
"""

from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from textora_engine.models import TranscriptSegment
from textora_engine.stt.base import BaseSTTProvider


class MockSTTProvider(BaseSTTProvider):
    """Deterministic mock STT provider for tests."""

    def __init__(
        self,
        mock_text: str = "This is a clean speech to text transcription generated by mock provider.",
        mock_language: str = "en",
        mock_confidence: float = 0.95,
    ):
        self.mock_text = mock_text
        self.mock_language = mock_language
        self.mock_confidence = mock_confidence

    @property
    def name(self) -> str:
        return "mock-stt"

    @property
    def model_name(self) -> str:
        return "mock-v1"

    def transcribe(
        self,
        audio_path: Path,
        language: Optional[str] = None,
        initial_prompt: Optional[str] = None,
    ) -> Tuple[List[TranscriptSegment], str, float]:
        segments = [
            TranscriptSegment(text=self.mock_text, start=0.0, duration=4.5, confidence=self.mock_confidence)
        ]
        lang = language if (language and language != "auto") else self.mock_language
        return segments, lang, self.mock_confidence

    def get_metadata(self) -> Dict[str, Any]:
        return {
            "stt_backend": self.name,
            "stt_model": self.model_name,
            "device": "mock",
            "compute_type": "mock",
        }
